version: '3.9'

services:
  kompas-web-dev:
    image: node:20-alpine
    container_name: kompas-web-dev
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  kompas-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    image: kompas-web:latest
    container_name: kompas-web
    ports:
      - "8080:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}

  supabase:
    image: supabase/postgres:15.1.1.70
    container_name: kompas-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "54322:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  supabase-data:
